### ISSUE TITLE
DomainMissingRoot error on some valid domains.

### ISSUE THREAD

**Issue by kenjoe41** [resyncgg/ripgen#3]
```bash
kenjoe41@testbox:~/test$ echo "googleapis.com" | ripgen -w words.txt
thread 'main' panicked at 'Failed to create Ripgen iterator: DomainMissingRoot', /home/kenjoe41/.cargo/registry/src/github.com-1ecc6299db9ec823/ripgen-0.1.3/src/main.rs:25:7
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: ripgen::main
```
Changed ^^ domain to `googleapiz.com` and it worked just fine. So it's not like it is resolving it or contains any special chars. Any reason this is happening?

**Comment by d0nutptr** [comment]
Hey @kenjoe41 ! 

googleapis.com is actually a [public suffix](https://publicsuffix.org/) like `github.io` or `co.uk`. To be more clear

`foo.googleapis.com` and `bar.googleapis.com` are not subdomains, but actually entirely distinct domains (and browsers will enforce all of the same logic around this too!)

I could probably make it, when you submit _just_ a publicsuffix, try to parse it like a regular domain though. Not 100% sure how that'd be done yet but can you help me understand why you need `ripgen` to work on `googleapis.com` instead of a specific domain?

**Comment by kenjoe41** [comment]
I fed `ripgen` a random domain list from a `domains.txt` file and got that error. There can be a number of use cases including trying to find domains/subdomains under the `googleapis.com` suffix with permutations from my `words.txt` file.
What do you think?

**Comment by d0nutptr** [comment]
Hey @kenjoe41 !

Good point :)

I've created a fix for this and now it should allow domains like `googleapis.com`. If you want to install the latest fix, you can `cargo install --force ripgen` and it should pull down the brand new update in the `ripgen_lib` dependency.
